### ISSUE TITLE
Access denied for user 'usr_wct'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by mbreemhaar** [WebCuratorTool/webcurator#53]
When I try to start the webapp, this is what I see in the log. The database username and password password set correctly in application.properties. I'm using MariaDB 10.3.31 on Ubuntu 20.04.3. As far as I'm aware, this should work. What could be going wrong?

```
2021-10-21 14:11:21.340 +0200 ERROR [schedulerFactory_Worker-10] o.q.c.ErrorLogger (QuartzScheduler.java:2407) - Job (DEFAULT.checkBandwidthTransitionsJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'checkForBandwidthTransition' on target class [class org.webcurator.core.harvester.coordinator.HarvestCoordinatorImpl] failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:580)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:475)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.webcurator.domain.HarvestCoordinatorDAOImpl$$EnhancerBySpringCGLIB$$cac26109.getBandwidthRestriction(<generated>)
	at org.webcurator.core.harvester.coordinator.HarvestBandwidthManagerImpl.getGlobalMaxBandwidth(HarvestBandwidthManagerImpl.java:101)
	at org.webcurator.core.harvester.coordinator.HarvestBandwidthManagerImpl.getCurrentGlobalMaxBandwidth(HarvestBandwidthManagerImpl.java:89)
	at org.webcurator.core.harvester.coordinator.HarvestBandwidthManagerImpl.checkForBandwidthTransition(HarvestBandwidthManagerImpl.java:200)
	at org.webcurator.core.harvester.coordinator.HarvestCoordinatorImpl.checkForBandwidthTransition(HarvestCoordinatorImpl.java:486)
	at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 common frames omitted
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:109)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:136)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:254)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:262)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:236)
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:86)
	at org.hibernate.internal.AbstractSharedSessionContract.beginTransaction(AbstractSharedSessionContract.java:468)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:535)
	... 19 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'usr_wct'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.GeneratedConstructorAccessor102.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:35)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:106)
	... 26 common frames omitted
```

**Comment by obrienben** [comment]
I would setup the db users again from scratch (maybe it's easier to just blow away the entire db and start again), and leave usr_wct with it's default pw and test again.
If that works, then we know to focus on troubleshooting the password change

**Comment by mbreemhaar** [comment]
@obrienben Thank you so much! With the default password everything seems to work fine. I will try to find out what went wrong and let you know as soon as I have a solution. If you have any idea what the problem might be, let me know. :-)

**Comment by mbreemhaar** [comment]
I tested some things and I found out that only the default password seems to work. Then, I tried changing the password in `application.properties` but leaving the default in MariaDB. The webapp still works fine after that, so it looks like the WCT is not looking at my the `schema.password` property in `application.properties`.

I double checked that other settings in `application.properties` do work fine by changing the port for the webapp, and after restarting the WCT it was indeed running on a different port.

So to me it looks like the password is somehow hardcoded in the webapp. Could that be the problem?

**Comment by hannakoppelaar** [comment]
No, the password is not hard-coded. But I think I'm beginning to see what might be going on: you say you have a schema.password in application.properties. I believe this property is being overridden by the one in application-local+mysql.properties, which is where all database properties are located.

You could either add an application-local+mysql.properties (with your own schema.password) in the working directory of the java command that is used to run webapp, or change schema.password in the application-local+mysql.properties inside the war file.

I hope that works.

**Comment by mbreemhaar** [comment]
That was indeed the problem! The password setting was being overridden by the `local+mysql` profile because `application.properties` by default contains this line: `spring.profiles.active=local+mysql`. I removed that line so it does not use that profile, and now everything works fine. Thanks a lot!
